#zuul网关
server:
  port: 7070
  tomcat:
    uri-encoding: UTF-8
spring:
  application:
    name: springcloud-zuul-server
  redis:
    port: 8039
    database: 0
    password: netsnapredis
    host: 192.168.155.65
#路由规则:  http://[网关地址]:[端口号]/[prefix]/[微服务实例id]/[请求地址路径]
zuul:
  routes:
    #由于路由id和微服务实例id相同，我们可以简化转发的配置
    service-article: /service-article/**             #配置微服务的路由Id,微服务的实力Id
#      path: /service-article/**  #请求路径(前缀)
#      service-id: service-article  #请求转发的微服务实例id
      #url: http://192.168.74.1:8001  #请求转发的微服务所在的ip地址
  prefix: /api                      #请求前缀
#eureka 配置信息
eureka:
  #自定义 eureka server的信息
  server:
    hostname: eureka
    port: 7000
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${eureka.server.hostname}:${eureka.server.port}/eureka/
#ip请求限制的参数配置
blackIp:
  continueCounts: ${counts:10} #ip连续请求次数
  timeInterval: ${interval:10} #ip判断的时间间隔,单位秒
  limitTimes: ${times:15} #限制的时间 单位秒

